#ifndef __OMAP_LGE_NVDATA_EMMC_H
#define __OMAP_LGE_NVDATA_EMMC_H
#define LGE_NVDATA_SECTOR_SIZE	0x200 
#define LGE_DYNAMIC_NVDATA_PARTITION_START_SECTOR	0x200 
#define LGE_DYNAMIC_NVDATA_PARTITION_LAST_SECTOR	0x200+511 
#define LGE_STATIC_NVDATA_PARTITION_START_SECTOR	0x300 
#define LGE_STATIC_NVDATA_PARTITION_LAST_SECTOR	0x300+511 
enum lge_dynamic_nvdata_offset {
	LGE_NVDATA_DYNAMIC_RESET_CAUSE_BACKUP_OFFSET = 508,
	LGE_NVDATA_DYNAMIC_REMOVE_FAT_OFFSET = 510,
	LGE_NVDATA_DYNAMIC_RESET_CAUSE_OFFSET 	= 512,  
	LGE_NVDATA_DYNAMIC_CRASH_DUMP_OFFSET 	= 514,  
	LGE_NVDATA_DYNAMIC_AP_CRASH_DUMP_OFFSET = 515,  
	LGE_NVDATA_DYNAMIC_FORCE_CRASH_OFFSET 	= 516,  
	LGE_NVDATA_DYNAMIC_FACTORY_RESET_STATUS_OFFSET 	= 518,  
	LGE_NVDATA_DYNAMIC_FBOOT_OFFSET 	= 520,  
	LGE_NVDATA_DYNAMIC_HARD_RESET_OFFSET = 526, 
	LGE_NVDATA_DYNAMIC_RTC_INIT_OFFSET = 528,	
	LGE_NVDATA_DYNAMIC_FRSTSTATUS3_OFFSET = 530,
	LGE_NVDATA_DYNAMIC_910K_DETECT_OFFSET	= 1024,  
	LGE_NVDATA_DYNAMIC_QEM_OFFSET			= 2048, 
	LGE_NVDATA_DYNAMIC_DEVICETEST_OFFSET	= 2052, 
	LGE_NVDATA_DYNAMIC_DEVICDTEST_DATE_OFFSET = 2060,
	LGE_NVDATA_DYNAMIC_MUIC_RETENTION_OFFSET = 2560, 
	LGE_NVDATA_DYNAMIC_SMPL_EN_OFFSET	= 2570,	
	LGE_NVDATA_DYNAMIC_SMPL_COUNT_OFFSET	= 2572,	
	LGE_NVDATA_DYNAMIC_WED_DOWNLOAD_OFFSET1 = 2580, 
	LGE_NVDATA_DYNAMIC_WED_DOWNLOAD_OFFSET2 = 2582,	 
	LGE_NVDATA_DYNAMIC_CHARGING_TEMP_OFFSET = 2600, 
	LGE_NVDATA_DYNAMIC_UBOOT_TIME = 4096
};
enum lge_static_nvdata_offset {
	LGE_NVDATA_STATIC_IMEI_OFFSET = 1024, 
	LGE_NVDATA_STATIC_910K_DETECT_OFFSET = 2048,
	LGE_NVDATA_STATIC_PID_DETECT_OFFSET     = 2050,
	LGE_NVDATA_STATIC_SECOND	= 2090,  
	LGE_NVDATA_STATIC_DOWNLOAD_FINISH	= 2046,
	LGE_NVDATA_STATIC_QEM_OFFSET		= 5116,  
	LGE_NVDATA_STATIC_DEVICETEST_OFFSET	= 5120, 
	LGE_NVDATA_STATIC_DEVICETEST_DATE_OFFSET = 5128,
	LGE_NVDATA_STATIC_FRSTSTATUS_OFFSET = 5200
};
#define LGE_NVDATA_RESET_CAUSE_VAL_USER_RESET	0x94
#define LGE_NVDATA_RESET_CAUSE_VAL_AP_CRASH		0xDE
#define LGE_NVDATA_RESET_CAUSE_VAL_CP_CRASH		0xAD
#define LGE_NVDATA_RESET_CAUSE_FACTORY_RESET	0x46
#define LGE_NVDATA_RESET_CAUSE_WEB_DOWNLOAD_RESET1	0x11
#define LGE_NVDATA_RESET_CAUSE_WEB_DOWNLOAD_RESET2	0x22
#define LGE_NDATA_CRASH_DUMP_INITIAL_VALUE	0x00
#define LGE_NDATA_CRASH_DUMP_ENABLE_VALUE	0xA5
#define LGE_NDATA_CRASH_DUMP_DISABLE_VALUE	0xB3
#define LGE_NVDATA_EMMC_ERR_SIZE_TOO_SMALL	-1;  
#define LGE_NVDATA_EMMC_ERR_SIZE_TOO_LARGE	-2; 
#define LGE_NVDATA_EMMC_ERR_SECTOR_MISMATCH	-3;
#define LGE_NVDATA_EMMC_ERR_ALIGN_MISMATCH	-4;
extern int lge_dynamic_nvdata_emmc_read(enum lge_dynamic_nvdata_offset offset,char* buf,int size);
extern int lge_dynamic_nvdata_emmc_write(enum lge_dynamic_nvdata_offset offset,char* buf,int size);
extern int lge_static_nvdata_emmc_write(enum lge_dynamic_nvdata_offset offset,char* buf,int size);
extern int lge_static_nvdata_emmc_read(enum lge_dynamic_nvdata_offset offset,char* buf,int size);
#endif
